# Server
server:
  port: 8080
logging:
  level:
    root: warn
    io.github.mangocrisp.spring.taybct.tool.core.websocket: DEBUG
    org.springframework.web.reactive.socket: DEBUG
    reactor.netty: DEBUG
spring:
  codec:
    max-in-memory-size: 100MB
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: dev
  application:
    name: exp-websocket-mvc
